

--1
CREATE VIEW WORKER_DETAIL
AS
SELECT TOP 100 * FROM PERSON

SELECT * FROM WORKER_DETAIL


--2
CREATE VIEW SALARY_DETAIL
AS
SELECT DESIGNATION.DESIGNATIONNAME,MAX(SALARY) AS MAXIMUM,MIN(SALARY) AS MINIMUM,SUM(SALARY) AS TOTAL FROM PERSON INNER JOIN DESIGNATION
ON PERSON.DESIGNATIONID=DESIGNATION.DESIGNATIONID
GROUP BY DESIGNATION.DESIGNATIONNAME

SELECT * FROM SALARY_DETAIL


--3
CREATE VIEW WORKER_ID
AS
SELECT FIRSTNAME,SALARY,JOININGDATE,DATEDIFF(YEAR,JOININGDATE,GETDATE()) AS DIFF FROM PERSON

SELECT * FROM WORKER_ID


--4
CREATE VIEW TOTAL_WORKER
AS
SELECT D.DEPARTMENTNAME,DD.DESIGNATIONNAME,COUNT(P.WORKERID) AS TOTAL_EMPLOYEE
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
INNER JOIN DESIGNATION DD
ON P.DESIGNATIONID=DD.DESIGNATIONID
GROUP BY D.DEPARTMENTNAME,DD.DESIGNATIONNAME

SELECT * FROM TOTAL_WORKER


--5
CREATE VIEW DONT_HAVE_DEPT
AS
SELECT FIRSTNAME FROM PERSON WHERE DESIGNATIONID IS NULL OR DEPARTMENTID IS NULL

SELECT * FROM DONT_HAVE_DEPT