
--1
CREATE FUNCTION WORKER_BY_DEPT(
	@DEPARTMENTID	INT
)
RETURNS TABLE
AS 
	RETURN (SELECT FIRSTNAME FROM PERSON WHERE DEPARTMENTID=@DEPARTMENTID)

SELECT * FROM DBO.WORKER_BY_DEPT(1)


--3
CREATE FUNCTION DATE_DIFF_DAY(
	@DATE1	DATETIME,
	@DATE2	DATETIME
)
RETURNS INT
AS
BEGIN
 RETURN (DATEDIFF(DAY,@DATE1,@DATE2))
END


SELECT DBO.DATE_DIFF_DAY('2022-08-01','2022-08-10')



--4
ALTER FUNCTION FUN_TOTAL_DAYS_BY_MONTH_AND_YEAR(@MONTH INT, @YEAR INT)
RETURNS INT
AS
BEGIN
		DECLARE @Date DATE = CAST(
                            CAST(@Year AS CHAR(4)) 
                            + RIGHT('0' + CAST(@Month AS VARCHAR(2)), 2)
                            + '01' AS DATE);
							
        RETURN DAY(EOMONTH(@DATE))

END

 select DBO.FUN_TOTAL_DAYS_BY_MONTH_AND_YEAR(2,2020)

