CREATE DATABASE PERSON_INFO

--1
SELECT P.PERSONNAME,D.DEPARTMENTCODE,D.DEPARTMENTNAME
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID

--2
SELECT D.DEPARTMENTNAME,MAX(P.SALARY) AS MAX_SALARY,MIN(P.SALARY) AS MIN_SALARY
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME

--3
SELECT D.DEPARTMENTNAME,SUM(P.SALARY) AS TOTAL_SALARY
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING SUM(P.SALARY)>100000

--4
SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME 
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE CITY='JAMNAGAR'

--5
SELECT P.PERSONNAME
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE D.DEPARTMENTID IS NULL

--6
SELECT D.DEPARTMENTNAME,COUNT(D.DEPARTMENTID)
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME

--7
SELECT CITY,AVG(SALARY)
FROM PERSON
WHERE CITY='AHMEDABAD'
GROUP BY CITY

--8
SELECT P.PERSONNAME+' EARNS '+CAST(SALARY AS VARCHAR)+' FROM DEPARTMENT '+D.DEPARTMENTNAME+' MONTHLY '
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID

--9
SELECT D.DEPARTMENTNAME,COUNT(P.PERSONID)
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING COUNT(P.PERSONID)=0

--10
SELECT P.CITY,D.DEPARTMENTNAME,SUM(P.SALARY) AS TOTAL_SALARY , MAX(P.SALARY) AS MAX_SALARY, MIN(P.SALARY) AS MIN_SALARY
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME,P.CITY

--11
SELECT DISTINCT(CITY) FROM PERSON

--12
SELECT D.DEPARTMENTNAME,COUNT(P.PERSONID)
FROM PERSON P INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING COUNT(P.PERSONID)>2

--13
SELECT LEFT(PERSONNAME,3)+RIGHT(CITY,3) FROM PERSON

--14
UPDATE PERSON SET SALARY=SALARY+SALARY*0.1
WHERE DEPARTMENTID = (SELECT DEPARTMENTID FROM DEPARTMENT WHERE DEPARTMENTNAME='COMPUTER')
--15
SELECT PERSONNAME FROM PERSON
WHERE DATEDIFF(DAY,JOININGDATE,GETDATE())>365